Update 07_Siamese.ipynb
When  I ran your notebook I get an error while converting the images from the dataloader:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-2f9549992df5> in <module>
      1 from torchvision import transforms
----> 2 im1 = transforms.ToPILImage()(batch[0][0]).convert("RGB")
      3 im2 = transforms.ToPILImage()(batch[1][0]).convert("RGB")

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torchvision/transforms/transforms.py in __call__(self, pic)
    134 
    135         """
--> 136         return F.to_pil_image(pic, self.mode)
    137 
    138     def __repr__(self):

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torchvision/transforms/functional.py in to_pil_image(pic, mode)
    140         pic = pic.mul(255).byte()
    141     if isinstance(pic, torch.Tensor):
--> 142         npimg = np.transpose(pic.numpy(), (1, 2, 0))
    143 
    144     if not isinstance(npimg, np.ndarray):

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
Therefore I did the conversion and now it works fine!